In [2]:
# import package
import numpy as np

# define 1D array
oneD_list = [1, 2, 3, 4, 5]
oneD_array = np.array(oneD_list)
print(oneD_array)

# define 2D array
twoD_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
twoD_array = np.array(twoD_list)
print(twoD_array)

# define 3D array
threeD_list = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
threeD_array = np.array(threeD_list)
print(threeD_array)

# dimension of array
oneD_array.ndim
twoD_array.ndim
threeD_array.ndim

# shape for each dimension, number of rows and columns
twoD_array.shape

# size for each dimension, total number of elements
twoD_array.size

# kind of data in array
twoD_array.dtype



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


dtype('int64')

In [22]:
# assign subset of existing array to new variable

print(oneD_array)
myview = oneD_array[1:4]
mycopy = oneD_array[1:4].copy()

print(myview)
print(mycopy)

# change value in the original array
oneD_array[2] = 20.0


# compare the two copies
print(myview, mycopy)


# check base for each copy
print(myview.base)
print(mycopy.base)







[ 1  2 20  4  5]
[ 2 20  4]
[ 2 20  4]
[ 2 20  4] [ 2 20  4]
[ 1  2 20  4  5]
None


In [29]:
# target a specific elements in the array

print(twoD_array)

# target number "5"
twoD_array[1, 1]
print(twoD_array[1, 1])

# show same element using [,]

twoD_array[1, 1]

# show "7" using [,]

print(twoD_array[2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
7


In [39]:
# select some contigous elements in the array (first rows, then columns)

bigger2D = np.array([[1,2,3,16,17],[4,5,6,18,19],[7,8,9,20,21],[10,11,12,22,23],[13,14,15,24,25]])
print(bigger2D)

print(bigger2D[1:3,1:4])
print(bigger2D[3:,3:])


# target non-contigious elements in the array

print(bigger2D[1:3,[0,2]])

[[ 1  2  3 16 17]
 [ 4  5  6 18 19]
 [ 7  8  9 20 21]
 [10 11 12 22 23]
 [13 14 15 24 25]]
[[ 5  6 18]
 [ 8  9 20]]
[[22 23]
 [24 25]]
[[4 6]
 [7 9]]


In [49]:
# simple calc with arrays

oneD_array
oneD2_array = np.array([2,3,4,5,6])

print(oneD2_array)

# multiply array with 2

print(oneD2_array*2)


# arr squared 2

print(oneD2_array**2)


# add arr together

print(oneD_array)
print(oneD2_array)
print(oneD_array+oneD2_array)


# arr * arr
print(oneD_array*oneD2_array)


[2 3 4 5 6]
[ 4  6  8 10 12]
[ 4  9 16 25 36]
[ 1  2 20  4  5]
[2 3 4 5 6]
[ 3  5 24  9 11]
[ 2  6 80 20 30]


In [54]:
# Boolean array, in this case "0" returns "false"

bool_array = np.array([0,1,0,2,3], dtype=bool)
bool_array


# use boolean array with comparison operator
print(bigger2D)
my_boolean_array = np.array(bigger2D < 10)
print(my_boolean_array)




[[ 1  2  3 16 17]
 [ 4  5  6 18 19]
 [ 7  8  9 20 21]
 [10 11 12 22 23]
 [13 14 15 24 25]]
[[ True  True  True False False]
 [ True  True  True False False]
 [ True  True  True False False]
 [False False False False False]
 [False False False False False]]


In [58]:
# aggregation functions

print(oneD_array)
print(oneD_array.mean())
print(oneD_array.min())
print(oneD_array.max())

[ 1  2 20  4  5]
6.4
1
20


In [67]:
# sorting

print(oneD_array)
print(oneD_array.sort())


# concatenate arrays

oneD3 = np.concatenate((oneD_array, oneD2_array))
print(oneD3)


# transpose 2D array

print(bigger2D)
print(bigger2D.T)




[ 1  2  4  5 20]
None
[ 1  2  4  5 20  2  3  4  5  6]
[[ 1  2  3 16 17]
 [ 4  5  6 18 19]
 [ 7  8  9 20 21]
 [10 11 12 22 23]
 [13 14 15 24 25]]
[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]
 [16 18 20 22 24]
 [17 19 21 23 25]]


In [4]:
zero_array = np.zeros(10, dtype=int)
print(zero_array)

print(np.arange(5,10,2))

np.linspace(0,100,11)

random_array = np.random.randint(1,10,10)
print(random_array)

random_array.reshape(2,5)
print(random_array.reshape(2,5))



[0 0 0 0 0 0 0 0 0 0]
[5 7 9]
[8 6 7 8 6 5 4 3 2 7]
[[8 6 7 8 6]
 [5 4 3 2 7]]
